#!/bin/bash

java -jar soot-4.1.0-jar-with-dependencies.jar -soot-class-path target/classes:target/test-classes:/usr/lib/jvm/<path-to-rt.jar> -output-format jimple -output-dir jimple-folder <instrumented-class-to-jimplify>
